#!/usr/bin/env/python

import argparse
import py2nb

# ---------------------
# Parse command line
# ---------------------

parser = argparse.ArgumentParser(
    description='python to Jupyter Notebook converter')
parser.add_argument('python_file',
                    help='name of the python input file')
parser.add_argument('notebook_file', nargs='?',
                    help='name of jupyter notebook output file')
args = parser.parse_args()

# ------------
# File names
# ------------

pyfile = args.python_file
nbfile = args.notebook_file
if nbfile is None:
    nbfile = pyfile.replace('.py', '.ipynb')

py2nb.py2nb(pyfile, nbfile)
